### PR TITLE
Added merch-design examples in README.md

### LINKED ISSUE #9: Add some merge examples (images) in the README.md
Could you assign me this issue please. I would like to add an examples section with some different merges in the README file

### PR DESCRIPTION
**Pull request by Fer-Bar**
Fixes #9 
- Added some cool merch-design examples in README.md.
addedex

### CODE REVIEW

**Comment by Fer-Bar** [comment]
Hey @Abdulmumin1 could you check my PR? I would appreciate it very much :)

**Comment by Fer-Bar** [comment]
Before you merge these changes could you add the hacktoberfest-accepted label to this PR please 🥺

**Comment by Abdulmumin1** [comment]
Those looks great, i love the first on and the last one, but not so with those in between.
it will be greate if you could edit all of them into a single image, because it taking alot of space in the readme.

and it would be better to move the examples to the bottom.

What do you think of these renders :eyes:  

merch(48)

merch(50)

@Fer-Bar

**Comment by Fer-Bar** [comment]
> Those looks great, i love the first on and the last one, but not so with those in between. it will be greate if you could edit all of them into a single image, because it taking alot of space in the readme.
> 
> and it would be better to move the examples to the bottom.
> 
> What do you think of these renders 👀
> 
> merch(48)
> 
> merch(50)
> 
> @Fer-Bar

Sure I can do it, give me some minutes and I added this changes. I love it those t-shirts 😎

**Comment by Fer-Bar** [comment]
Hey @Abdulmumin1 I updated mi PR could you check the changes? And **before you merge these changes** could you add the _**hacktoberfest-accepted**_ label to this PR please 🥺

**Review by Abdulmumin1 — CHANGES_REQUESTED** [review]
looks better!

**Comment by Abdulmumin1** [comment]
> dated mi PR could you check the changes? And **before you merge these changes** could you add the _**hacktoberfest-accepted**_ label to this PR please pleading_face

**sure,** but you don't need to tag `hacktoberfest-accepted` for you PR to count!

**Comment by Abdulmumin1** [comment]
#### Big sorry for troubling you so much, but can you also please remove the unused images you added.

**Comment by Fer-Bar** [comment]
Done @Abdulmumin1 . I am happy to contribute. Happy Hacktoberfest 🥳

**Review by Abdulmumin1 — APPROVED** [review]

**Review by Abdulmumin1 — APPROVED** [review]

**Pull request merged**
